# Generated by Django 6.0.3 on 2026-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='name',
        ),
        migrations.AddField(
            model_name='opinion',
            name='nome',
            field=models.CharField(default=11111111111111111111111111111111111, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
